baseURL = "https://blog.colachg.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "cola's blog"
theme = "anatole"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "Cola"
author = "Cola Chen"
description = "Sometimes life is amazing."
profilePicture = "images/rockman.jpeg"
oldContentWarning = true
oldContentDuration = 365

gtagId = "G-GV05N8LYQ"
#contentratio = 0.8
hidesidebar = true
googleSiteVerify = "yx5n7Uc0JFAgDNDwt-B7cbI0RH3qbXV4SpPDnbgv0HQ"
enableRobotsTXT = true
rssFullContent = true

[params.utterances]
repo = "colachg/colachg.github.io"
issueTerm = "pathname"
theme= "preferred-color-scheme"

  [[params.socialIcons]]
  icon = "fab fa-github"
  title = "GitHub"
  url = "https://github.com/colachg"

  [[params.socialIcons]]
  icon = "fab fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/cola-chen-395aba117/"

  [[params.socialIcons]]
  icon = "fas fa-envelope"
  title = "e-mail"
  url = "mailto:colachg@gmail.com"

[Languages]
    [Languages.en]
    title = "Cola"
    description = "Sometimes life is amazing."
    weight = 1
    LanguageName = "ENGLISH"
    contentDir = "content/en"
    [[Languages.en.menu.main]]
    name = "Home"
    identifier = "en"
    weight = 100
    url = "/"
    [[Languages.en.menu.main]]
    name = "Posts"
    identifier = "posts"
    weight = 200
    url = "/posts"
    [[Languages.en.menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about"

    [Languages.cn]
    title = "可乐橙"
    description = "有时生活超乎想象。"
    weight = 2
    LanguageName = "中文"
    contentDir = "content/cn"
    [[Languages.cn.menu.main]]
    name   = "主页"
    identifier = "主页"
    weight = 100
    url    = "/"
    [[Languages.cn.menu.main]]
    name = "博文"
    identifier = "博文"
    weight = 200
    url = "/posts"